### DISCUSSION TITLE
How to make custom controls fade out after a second with no mouse or touch events...

### DISCUSSION THREAD

**Discussion by rchrdnsh** [vidstack/player#893] [Q&A]
Hi all,

Starting to make a custom controls section for the player and I noticed that the controls don't fade out after I move my mouse away after any period of time...just curious how I can make that happen.

Thank you!

XD

**Comment by mihar-22** [comment]
By default, controls should fade out after 2.5s of user inactivity during playback. Do note, we'll be adding more configuration options following the next release (e.g., hide when paused too).

You can style them to hide like so:

```css
/* Hide controls while media is loading, or user is idle. */
media-player:not([data-can-play]) .media-controls,
media-player[data-user-idle] .media-controls {
  opacity: 0;
  pointer-events: none;
}
```

**Comment by rchrdnsh** [comment]
hmmmm...don't think it works...

Got the following markup:

```html
<media-player
        title="LSTV Live Stream"
        stream-type="live"
        src="https://media.streambrothers.com:1936/8228/8228/playlist.m3u8"
        poster="/graphics/lstv-poster.jpg"
        aspect-ratio="16/9"
        crossorigin="true"
        muted="true"
        autoplay="true"
        playsinline="true"
      >
        <media-outlet>
          <media-poster alt="The LSTV Logo."></media-poster>
        </media-outlet>
        <div class='player-controls'>
          <media-mute-button></media-mute-button>
          <media-play-button></media-play-button>
          <div class=screen-controls>
            <media-fullscreen-button></media-fullscreen-button>
            <media-pip-button></media-pip-button>
          </div>
        </div>
      </media-player>
```

...and the css:

```css
media-player {
    width: 100%;
    height: auto;
    border-radius: 12px;
    overflow: hidden;
    aspect-ratio: 16 / 9;
    border: 2px solid white;
    outline: 2px solid var(--brand-color);
  }

  .player-controls {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(3, 1fr);
    padding: 8px;
  }

  /* Hide controls while media is loading, or user is idle. */
  media-player:not([data-can-play]) .player-controls,
  media-player[data-user-idle] .player-controls {
    opacity: 0;
    pointer-events: none;
  }

  :global(media-player[data-user-idle] .player-controls) {
    opacity: 0;
    pointer-events: none;
  }

  media-play-button {
    grid-row: 2 / 3;
    grid-column: 2 / 3;
    color: white;
    background-color: var(--brand-color);
    opacity: 0.75;
    border-radius: 32px;
    width: 56px;
    height: 56px;
    place-self: center;
  }

  media-mute-button {
    width: 56px;
    height: 56px;
  }

  .screen-controls {
    grid-row: 3 / 4;
    grid-column: 3 / 4;
    place-self: end;
  }

  media-fullscreen-button, media-pip-button {
    width: 56px;
    height: 56px;
  }
```

...but svelte is telling me that:

```css
  media-player[data-user-idle] .player-controls {
    opacity: 0;
    pointer-events: none;
  }
  ```
  
  ...so I wrap it in a global tag:
  
  ```
    :global(media-player[data-user-idle] .player-controls) {
    opacity: 0;
    pointer-events: none;
  }
  ```
  
  ...but still not control fade after being idle for many seconds...
  
  not sure if I'm doing something wrong or not...

**Comment by rchrdnsh** [comment]
ugh...css...I simply moved those styles to the end of the css stack and it works now...


...argh...

**Comment by rchrdnsh** [comment]
This is the final css that works, in this order, for anybody else that might need this:

```css
media-player {
    width: 100%;
    height: auto;
    border-radius: 12px;
    overflow: hidden;
    aspect-ratio: 16 / 9;
    border: 2px solid white;
    outline: 2px solid var(--brand-color);
  }

  .player-controls {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(3, 1fr);
    padding: 4px;
    transition: all 300ms ease;
  }

  media-play-button {
    grid-row: 2 / 3;
    grid-column: 2 / 3;
    color: white;
    background-color: var(--brand-color);
    border: 4px solid white;
    opacity: 0.75;
    border-radius: 32px;
    width: 64px;
    height: 64px;
    place-self: center;
  }

  .volume-controls {
    grid-row: 3 / 4;
    grid-column: 1 / 2;
    align-self: end;
    display: grid;
    grid-auto-flow: column;
    grid-template-columns: min-content 1fr;
    align-items: center;
  }
  
  media-mute-button {
    width: 56px;
    height: 56px;
  }

  .screen-controls {
    grid-row: 3 / 4;
    grid-column: 3 / 4;
    place-self: end;
    display: grid;
    grid-auto-flow: column;
  }

  media-fullscreen-button, media-pip-button {
    width: 56px;
    height: 56px;
  }

  media-player:not([data-can-play]) .player-controls {
    opacity: 0;
    pointer-events: none;
  }

  :global(media-player[data-user-idle] .player-controls) {
    opacity: 0;
    pointer-events: none;
  }
```
