### DISCUSSION TITLE
How to force a specific aspect ratio?

### DISCUSSION THREAD

**Discussion by AgentSmith0** [vidstack/player#978] [Q&A]
Is it possible to set the aspect ratio for a video like with the `ratio` option in Plyr?

**Comment by mihar-22** [comment]
We just recommend CSS now:

```css
media-player {
  aspect-ratio: 16 / 9;
}
```

If you're using React we make it easier and apply it as a style:

```tsx
<MediaPlayer aspectRatio="16/9">
```
