### ISSUE TITLE
Markers in seeker

### ISSUE THREAD

**Issue by thisKeeWord** [vidstack/player#1052]
### Describe:

Chapters are a great addition. In terms of a marker (rather than a chapter) in the seeker, would it be possible to show markers (equivalent to a 0 second duration chapter). The only way a user can currently see it is by going to the "events" log in the video player menu
![Screenshot 2023-12-13 at 11 26 38 AM](https://github.com/vidstack/player/assets/13548758/2a20af1e-6815-4332-a81f-63392a8d5b3b)

### Anything else?
Is there a way to display both chapter titles if the start & end times are the same? I understand this would be more of an edge case, but to preface we're hoping to also use the player to track events (ex: door opened).
![Screenshot 2023-12-13 at 11 47 34 AM](https://github.com/vidstack/player/assets/13548758/94f50503-d15e-487f-9348-377232cac63d)

**Comment by mihar-22** [comment]
## Markers

Markers are the left edge (start) and right edge (end) of each chapter. You can customize the default layout to show simple markers like so:

```css
.vds-time-slider {
  --media-slider-chapter-hover-transform: none;
}

.vds-slider-chapter {
  margin-right: 0;
}

.vds-slider-track {
  border-radius: 0;
}

.vds-slider-chapter::after {
  content: '';
  position: absolute;
  left: 0;
  width: 3px;
  height: 5px;
  background-color: red;
  z-index: 10;
}
```

<img width="952" alt="image" src="https://github.com/vidstack/player/assets/14304599/d2e97b83-2498-4ba9-98e5-d44ad3947f64">

## Chapters

> Is there a way to display both chapter titles if the start & end times are the same?

I believe this already works. Feel free to open a new issue if anything is wrong :)
