### ISSUE TITLE
Documentation: css `media-ended` attribute is supposed to be `ended`?

### ISSUE THREAD

**Issue by pietrop** [vidstack/player#680]
Looking at [Play Button](https://www.vidstack.io/docs/player/react/components/ui/play-button/) docs and trying out the tip at the bottom of the page

>You can extend the preview above by adding a replay SVG icon, and showing it whilst hiding the play icon when the `media-ended` attribute is present.

However I only got it to work, when I changed it to `ended` instead of `media-ended`  ` vds-media[ended]`

(I figured that out by inspecting the attributes on the`vds-media` element in the browser)

<details><summary>For context this is the CSS I was using </summary>

```css
vds-play-button {
  position: relative;
  width: 28px;
  height: 28px;
  border-radius: 4px;
  cursor: pointer;
  color: white;
}

vds-play-button > svg {
  /** `absolute` so icons are placed on top of each other. */
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 1;
  transition: opacity ease 150ms;
}

vds-media[paused] .media-pause-icon {
  opacity: 0;
}

vds-media:not([paused]):not([media-ended]) .media-play-icon {
  opacity: 0;
} 

 vds-media[ended] .media-play-icon {
    opacity: 0;
} 

vds-media:not([ended]) .media-replay-icon {
    opacity: 0;
} 

vds-media[ended] .media-replay-icon {
    opacity: 1;
}
```

</details>

I can see originally in [this version](https://github.com/vidstack/player/blob/7dcb6e1e7867b135f08b9fbb5781c87f6429ac2b/CHANGELOG.md#010-2021-12-10) it was set to be `media-ended` https://github.com/vidstack/player/commit/1778126c2296b64109279332f5e079828c13889f

But the code might have change since that as I don't see that logic in the component now in main [packages/player/src/ui/play-button/PlayButtonElement.ts](https://github.com/vidstack/player/blob/main/packages/player/src/ui/play-button/PlayButtonElement.ts)

I am happy to do a PR but wanted to double check if it's a matter of updating the docs or the code?
