### ISSUE TITLE
[Community skin] --audio-controls-color does not apply on all elements

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#855]
### Current Behavior:

```css
media-community-skin[data-audio] {
  --audio-controls-color: xxx;
}
```

The color remain `#f5f5f5`.

### Expected Behavior:

The color changed correctly.

### Reason

<img width="947" alt="image" src="https://github.com/vidstack/player/assets/33315834/c5df41ef-4087-465f-beef-89c01c96b68d">

Through these buttons are to `--audio-controls-color` by `:where(media-community-skin[data-audio] [part~='media-ui'])`

but `:where(media-player [data-media-button])` has a higher priority setting it to `var(--media-button-color, #f5f5f5)`
