### ISSUE TITLE
on player hover, only put scrim on controls and not the entire video

### ISSUE THREAD

**Issue by younes0** [vidstack/player#873]
https://github.com/vidstack/player/blob/b57db0be1768a6f8c852c068df42b6fc32fda375/packages/vidstack/src/player/skins/community/video.css#L48

instead of putting gray overlay/scrim on the whole player, we could put a fading overlay/scrim effect on controls only (like Youtube):
```css
:where(media-community-skin[data-video] div[part="scrim"]) {
  background: linear-gradient(
    180deg,
    transparent 75%,
    rgba(0, 0, 0, 0.75) 100%
  );
}
```
